# [[plugins]]
# repo = 'rcmdnk/vim-markdown'
# on_ft = ['md', 'markdown']

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
on_ft = ['py']
